using System.Data.Common;
using System.Diagnostics.CodeAnalysis;
using Npgsql;
using Testcontainers.PostgreSql;
using Testcontainers.Xunit;
using Xunit;
using Xunit.Sdk;

namespace CoreBankDemo.Persistence.IntegrationTests.Infrastructure;

/// <summary>
/// The single, amortized PostgreSQL container for this whole assembly (ADR-016
/// tier 2). Registered as an xUnit v3 assembly fixture (see
/// <c>AssemblyFixture.cs</c>) so the cold-start cost is paid at most once per
/// test run — never per test class and never per test case.
/// </summary>
/// <remarks>
/// <para>
/// The container binds a generated host port (Testcontainers' default) — never
/// a fixed one — so a developer's own PostgreSQL on 5432, a running AppHost,
/// and a parallel test run cannot collide, and so cancelled runs leave no
/// fixed-port residue.
/// </para>
/// <para>
/// Mutable state is isolated per test by <see cref="CreateDatabaseAsync"/>,
/// which hands out a freshly created, uniquely named database inside this one
/// container. Startup is bounded by <see cref="StartupTimeout"/>: when Docker
/// is missing or unhealthy the target fails loudly with remediation context
/// instead of hanging, and it is never silently skipped or reported green.
/// </para>
/// </remarks>
public sealed class PostgresContainerFixture()
    : DbContainerFixture<PostgreSqlBuilder, PostgreSqlContainer>(DiagnosticSink.Instance)
{
    /// <summary>Bounded wait for image pull plus container readiness; a cold pull is the slow case.</summary>
    public static readonly TimeSpan StartupTimeout = TimeSpan.FromMinutes(5);

    /// <summary>Bounded wait for any test that expects to block on a row lock or a competing writer.</summary>
    public static readonly TimeSpan LockWaitTimeout = TimeSpan.FromSeconds(30);

    public override DbProviderFactory DbProviderFactory => NpgsqlFactory.Instance;

    /// <summary>
    /// Admin connection string for the container's maintenance database, used
    /// only to create and drop the per-test databases below. Its host port is
    /// generated by Testcontainers, never assumed.
    /// </summary>
    private string AdminConnectionString => Container.GetConnectionString();

    protected override PostgreSqlBuilder Configure() => new(PostgresImage.Tag);

    /// <inheritdoc />
    protected override async ValueTask InitializeAsync()
    {
        using var startupTimeout = new CancellationTokenSource(StartupTimeout);

        try
        {
            await base.InitializeAsync().AsTask().WaitAsync(startupTimeout.Token);
        }
        catch (Exception exception)
        {
            throw new InvalidOperationException(BuildUnavailableMessage(exception), exception);
        }
    }

    /// <summary>
    /// Creates a fresh, uniquely named database inside the shared container and
    /// returns its connection string. Two tests running in parallel therefore
    /// never see each other's rows, locks, or cleanup.
    /// </summary>
    public async Task<string> CreateDatabaseAsync(string label, CancellationToken cancellationToken)
    {
        var databaseName = UniqueDatabaseName(label);

        await using (var connection = new NpgsqlConnection(AdminConnectionString))
        {
            await connection.OpenAsync(cancellationToken);
            await using var command = connection.CreateCommand();
            command.CommandText = $"CREATE DATABASE \"{databaseName}\"";
            await command.ExecuteNonQueryAsync(cancellationToken);
        }

        return new NpgsqlConnectionStringBuilder(AdminConnectionString) { Database = databaseName }.ConnectionString;
    }

    /// <summary>
    /// Drops an isolated database created by <see cref="CreateDatabaseAsync"/>,
    /// forcibly terminating any connection a failed test left behind so a red
    /// run cleans up as reliably as a green one.
    /// </summary>
    public async Task DropDatabaseAsync(string connectionString)
    {
        var databaseName = new NpgsqlConnectionStringBuilder(connectionString).Database!;
        NpgsqlConnection.ClearAllPools();

        try
        {
            await using var connection = new NpgsqlConnection(AdminConnectionString);
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DROP DATABASE IF EXISTS \"{databaseName}\" WITH (FORCE)";
            await command.ExecuteNonQueryAsync();
        }
        catch (Exception exception) when (exception is NpgsqlException or TimeoutException)
        {
            // Cleanup diagnostics stay visible instead of being swallowed, but a
            // teardown failure must not overwrite the verdict of the test that
            // just ran.
            ReportCleanupFailure(databaseName, exception);
        }
    }

    [ExcludeFromCodeCoverage(Justification = "Teardown diagnostics path; only reachable when container cleanup itself fails.")]
    private static void ReportCleanupFailure(string databaseName, Exception exception) =>
        TestContext.Current.SendDiagnosticMessage(
            "Failed to drop isolated test database '{0}': {1}", databaseName, exception.Message);

    private static string UniqueDatabaseName(string label)
    {
        var sanitized = new string([.. label.Where(char.IsLetterOrDigit)]).ToLowerInvariant();
        if (sanitized.Length > 24)
        {
            sanitized = sanitized[^24..];
        }

        return $"cbd_{sanitized}_{Guid.NewGuid():N}";
    }

    internal static string BuildUnavailableMessage(Exception exception) =>
        $"""
         The PostgreSQL persistence integration tier could not start its container within {StartupTimeout.TotalMinutes:0} minutes.

         This target requires a working container runtime; it is never skipped or reported green without one.
           * Check the runtime is up:       docker info
           * Check the pinned image pulls:  docker pull {PostgresImage.Tag}
           * Run the Docker-free tier only: dotnet test CoreBankDemo.UnitTests.slnf

         Underlying failure: {exception.Message}
         """;

    /// <summary>
    /// Forwards Testcontainers' own container/pull logs into xUnit's diagnostic
    /// stream, so a slow or failing cold start is diagnosable from the test log
    /// rather than invisible.
    /// </summary>
    [ExcludeFromCodeCoverage(Justification = "Diagnostic plumbing for container logs; carries no assertable behavior.")]
    private sealed class DiagnosticSink : IMessageSink
    {
        internal static readonly DiagnosticSink Instance = new();

        public bool OnMessage(IMessageSinkMessage message)
        {
            TestContext.Current.SendDiagnosticMessage("{0}", message);
            return true;
        }
    }
}
