<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Include>[CoreBankDemo.PaymentsAPI]*</Include>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CoreBankDemo.PaymentsAPI\CoreBankDemo.PaymentsAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

</Project>
